; Our socket path name must be < 106 characters.
; Naming the file s.sock helps.
[unix_http_server]
file=%(here)s/s.sock

[supervisord]
umask=0077
directory=%(here)s/../..
logfile=%(here)s/supervisord.log
pidfile=%(here)s/supervisord.pid

[supervisorctl]
serverurl=unix://%(here)s/s.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

; [program:celery]
; command=celery -A gstcomply.celery worker -l info
; startsecs=3
; stdout_logfile=%(here)s/%(program_name)s/%(program_name)s.log
; stderr_logfile=%(here)s/%(program_name)s/%(program_name)s.err

; [program:cron]
; command=celery -A gstcomply.celery beat -l info
; startsecs=3
; stdout_logfile=%(here)s/%(program_name)s/%(program_name)s.log
; stderr_logfile=%(here)s/%(program_name)s/%(program_name)s.err

[program:gunicorn]
command=gunicorn -c %(here)s/gunicorn/conf.py config.wsgi
startsecs=2
stdout_logfile=%(here)s/%(program_name)s/%(program_name)s.log
stderr_logfile=%(here)s/%(program_name)s/%(program_name)s.err

[program:run_tasks]
command=python -m scripts.run_tasks
startsecs=2
stdout_logfile=%(here)s/%(program_name)s/%(program_name)s.log
stderr_logfile=%(here)s/%(program_name)s/%(program_name)s.err

[program:autosync]
command=python -m scripts.autosync_scheduler
startsecs=2
stdout_logfile=%(here)s/%(program_name)s/%(program_name)s.log
stderr_logfile=%(here)s/%(program_name)s/%(program_name)s.err


; vim:filetype=dosini
