/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SyncInvoicesEntrypointArg {
  id: string;
  syncUrl: string;
}
export interface SyncInvoicesResponse {
  session_uuid: string;
  urls: SyncInvoicesUrls;
}
export interface SyncInvoicesUrls {
  sync_invoices: string;
  status: string;
}
export interface SyncInvoicesStatusResponse {
  completed: boolean;
  errors: string[];
}
