# Generated by Django 3.0 on 2020-03-18 01:26

import cz_utils.django.db.fields
from django.db import migrations, models
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('schema_name', cz_utils.django.db.fields.TrimmedCharField(db_index=True, help_text="The name of the tenant/customer's schema.", max_length=255)),
                ('scheduled_time', models.DateTimeField(help_text='The time at which this task is scheduled.')),
                ('rescheduled_time', models.DateTimeField(blank=True, help_text='The time at which this task is re-scheduled, in case of failure.', null=True)),
                ('invocation_time', models.DateTimeField(blank=True, help_text='The time at which this task is executed. If a task is in the running state for a very long time, we can take measures to retry it.', null=True)),
                ('completion_time', models.DateTimeField(blank=True, help_text='The time at which this task completed. Helps us know the duration of the Task.', null=True)),
                ('status', models.PositiveIntegerField(choices=[(11000, 'Initial'), (11001, 'Running'), (11002, 'Completed Successfully'), (11003, 'Task has timed-out'), (11004, 'Failed'), (11005, 'Requested task is not a valid function'), (11006, "Won't retry after this Failure"), (11007, 'Transient failure (not in our control)'), (11008, 'Too much for Lambda'), (11009, 'Failed (because of software bug)'), (11010, 'Failed because of some timing error')], db_index=True, default=11000, help_text='The status of this task.')),
                ('tasktype', models.PositiveIntegerField(choices=[(878, 'Lambda'), (879, 'Fargate')], help_text='The type of task. Used for scheduling on Lambda/Fargate', null=True)),
                ('num_tries', models.PositiveIntegerField(default=0, help_text='The number of times we have tried to excute this task.')),
                ('traceback_text', cz_utils.django.db.fields.CzTextField(blank=True, help_text='Any traceback, in case of exception')),
                ('remarks', cz_utils.django.db.fields.CzTextField(blank=True)),
                ('metadata', jsonfield.fields.JSONField(default=dict, editable=False)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('schema_name', cz_utils.django.db.fields.TrimmedCharField(db_index=True, help_text="The name of the tenant/customer's schema.", max_length=255)),
                ('transaction_identifier', cz_utils.django.db.fields.TrimmedCharField(db_index=True, help_text='The unique transaction identifier. https://groups.google.com/forum/#!msg/gst-suvidha-provider-gsp-discussion-group/6K0edbW6ooI/iI1cpR4-AAAJ', max_length=255)),
                ('url', models.URLField(help_text='The URL Path of the request.', max_length=1024)),
                ('headers', jsonfield.fields.JSONField(blank=True, default=dict, help_text='The HTTP headers.')),
                ('payload', jsonfield.fields.JSONField(blank=True, default=dict, help_text='The unencrypted JSON data sent in the payload.')),
                ('status_code', models.PositiveIntegerField(blank=True, help_text='The HTTP Status code of the response.', null=True)),
                ('elapsed', models.DurationField(blank=True, help_text='The time time it took to get the response. http://docs.python-requests.org/en/latest/api/#requests.Response.elapsed', null=True)),
                ('response', jsonfield.fields.JSONField(blank=True, default=dict, help_text='The decrypted response data from received from GSTN.')),
                ('raw_response', models.BinaryField(blank=True, help_text='The response content received from GSTN. Used only in the case of error responses when we are not able to set the `response` field.', null=True)),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
