# Generated by Django 3.0 on 2020-03-18 01:26

import cz_utils.django.db.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import re
import taxmaster.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('abbreviation', cz_utils.django.db.fields.TrimmedCharField(help_text='an abbreviation of the currency, such as INR', max_length=255, unique=True)),
                ('name', cz_utils.django.db.fields.TrimmedCharField(help_text='the full name of the currency', max_length=255, unique=True)),
                ('exchange_rate', models.DecimalField(decimal_places=6, help_text='the reference exchange rate to convert to the home currency', max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Exchange Rate')),
                ('is_home', models.BooleanField(null=True, blank=True, help_text='is this the home currency for your company?. If not,\n        leave this field unset. Only one currency can be the home\n        currency.', unique=True, verbose_name='Is Home')),
            ],
            options={
                'verbose_name_plural': 'currencies',
                'ordering': ('abbreviation',),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FilingStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('gstin', cz_utils.django.db.fields.CzUppercaseField(db_index=True, help_text='The 15-digit GSTIN Number', max_length=255, validators=[taxmaster.models.validate_gstin], verbose_name='GSTIN')),
                ('return_period', models.DateField(help_text='The period for which this Tax Return is to be filed for.', verbose_name='Return Period')),
                ('status', cz_utils.django.db.fields.TrimmedCharField(blank=True, max_length=255, verbose_name='Filing status')),
                ('mode_of_filing', cz_utils.django.db.fields.TrimmedCharField(blank=True, max_length=255, verbose_name='Mode of Filing')),
                ('date_of_filing', models.DateField(blank=True, null=True, verbose_name='Date of Filing')),
                ('acknowledgement_number', cz_utils.django.db.fields.TrimmedCharField(blank=True, max_length=255, verbose_name='Acknlowledgement Number')),
                ('return_type', models.PositiveSmallIntegerField(blank=True, choices=[(8000, 'GSTR-1 Monthly Outward Supply'), (8001, 'GSTR-2 Monthly Inward Supply'), (8002, 'GSTR-3 Monthly GST Return'), (8003, 'GSTR-1A Monthly Outward Supply (Auto)'), (8004, 'GSTR-2A Monthly Inward Supply (Auto)'), (8005, 'GSTR-3B Consolidated Monthly GST Return'), (8006, 'GSTR-4 - Quarterly Return for Registered Person opting for Composition Levy'), (8007, 'GSTR-6 - Return for Input Service Distributor'), (8018, 'GSTR-6A - 6A Return for Input Service Distributor'), (8008, 'GSTR-9 - Annual Return'), (8009, 'GSTR-10 - Final Return'), (8010, 'ITC-01 - Declaration for claim of input tax credit under sub-section (1) of section 18'), (8011, 'ITC-02 - Declaration for transfer of ITC in case of sale, merger, demerger, amalgamation, lease or transfer of a business under sub-section (3) of section 18'), (8012, 'ITC-03 - Declaration for intimation of ITC reversal/payment of tax on inputs held in stock, inputs contained in semi-finished and finished goods held in stock and capital goods under sub-section (4) of section 18'), (8013, 'ITC-04 - Details of goods/capital goods sent to job worker and received back'), (8014, 'TRAN-1 Transition Return 1'), (8015, 'TRAN-2 Transition Return 2'), (8016, 'TRAN-3 Transition Return 3'), (8017, 'GSTR-9A Annual Return (For Composition Taxpayer)'), (8019, 'GSTR-9C Annual Return Audit'), (8020, 'GSTR-4A - Quarterly Return for Registered Person opting for Composition Levy'), (8021, 'RET-1 Normal GST Return'), (8022, 'RET-2 Sahaj GST Return'), (8023, 'RET-3 Sugam GST Return'), (8024, 'ANX-1 Annexure of Outward Supplies'), (8025, 'ANX-2 Annexure of Inward Supplies'), (8026, 'RET-1A Normal GST Return (Amendment)'), (8027, 'RET-2A Sahaj GST Return (Amendment)'), (8028, 'RET-3A Sugam GST Return (Amendment)')], help_text='The type of this Tax Return.', null=True, verbose_name='Return Type')),
                ('return_type_string', cz_utils.django.db.fields.TrimmedCharField(blank=True, max_length=255, verbose_name='Return Type String')),
                ('metadata', jsonfield.fields.JSONField(default=dict, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pincode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('pincode', models.PositiveIntegerField(db_index=True, unique=True)),
                ('details_available', models.BooleanField()),
                ('city', cz_utils.django.db.fields.TrimmedCharField(max_length=255)),
                ('state', cz_utils.django.db.fields.TrimmedCharField(max_length=255)),
                ('statecode', cz_utils.django.db.fields.TrimmedCharField(max_length=255)),
                ('city_slug', models.SlugField(blank=True, max_length=255)),
                ('google_response', jsonfield.fields.JSONField(editable=False, help_text='The response from Google about this PIN Code search', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PortCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('code', cz_utils.django.db.fields.TrimmedCharField(max_length=255, unique=True, verbose_name='Port Code')),
                ('name', cz_utils.django.db.fields.TrimmedCharField(max_length=255, verbose_name='Port Name')),
            ],
            options={
                'ordering': ('name',),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('name', cz_utils.django.db.fields.TrimmedCharField(max_length=255, unique=True, verbose_name='State')),
                ('statetype', models.PositiveIntegerField(choices=[(1, 'State'), (2, 'Union Territory'), (3, 'International (Outside India)')])),
                ('code', cz_utils.django.db.fields.TrimmedCharField(max_length=255, unique=True)),
                ('alphaCode', cz_utils.django.db.fields.TrimmedCharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('name', cz_utils.django.db.fields.TrimmedCharField(help_text='The Unit Quantity Code (UQC)', max_length=255, unique=True, verbose_name='UQC')),
                ('name_for_gstn', cz_utils.django.db.fields.TrimmedCharField(default='OTH', help_text='The UQC that we should use for filing GST Return. This is because, some customers prefer to use a UQC that makes sense to them, like Carat, but GSTN does not accept this as a valid one. This column specifies the mapping.', max_length=255, verbose_name='UQC for filing')),
                ('long_name', cz_utils.django.db.fields.TrimmedCharField(help_text='Unit name', max_length=255, verbose_name='Name')),
            ],
            options={
                'ordering': ('name',),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='TaxPayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('pan', cz_utils.django.db.fields.CzUppercaseField(blank=True, db_index=True, max_length=255, validators=[django.core.validators.RegexValidator(message='The specified number is not a valid PAN.', regex=re.compile('^[A-Z]{4}[A-Z0-9][0-9]{4}[A-Z]$', 2))], verbose_name='PAN Number')),
                ('gstin', cz_utils.django.db.fields.CzUppercaseField(db_index=True, help_text='The 15-digit GSTIN Number', max_length=255, unique=True, validators=[taxmaster.models.validate_gstin], verbose_name='GSTIN')),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('legal_name', cz_utils.django.db.fields.TrimmedCharField(db_index=True, help_text='The Legal Name of the Tax Payer', max_length=255, verbose_name='Legal Name')),
                ('trade_name', cz_utils.django.db.fields.TrimmedCharField(blank=True, db_index=True, help_text='The Trade Name of the Tax Payer', max_length=255, verbose_name='Trade Name')),
                ('pincode', cz_utils.django.db.fields.TrimmedCharField(blank=True, max_length=255, verbose_name='PIN Code')),
                ('valid', models.BooleanField(help_text='Whether this TIN number is a valid one.')),
                ('registration_date', cz_utils.django.db.fields.CzDateField(blank=True, help_text='The date of registration of this Tax Payer.', null=True)),
                ('cancellation_date', cz_utils.django.db.fields.CzDateField(blank=True, help_text="The date of cancellation of this Tax Payer's registration.", null=True)),
                ('gstn_response', jsonfield.fields.JSONField(default=dict, editable=False, help_text='The response from GSTN about this Tax Payer')),
                ('portal_response', jsonfield.fields.JSONField(editable=False, help_text='The response from GSTN Portal (not API) about this Tax Payer', null=True)),
                ('ewb_response', jsonfield.fields.JSONField(default=dict, editable=False, help_text='The response from the E-Way Bill website about this Tax Payer')),
                ('metadata', jsonfield.fields.JSONField(default=dict, editable=False)),
                ('pincode_obj', cz_utils.django.db.fields.CzForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='taxmaster.Pincode')),
                ('state_obj', cz_utils.django.db.fields.CzForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='taxmaster.State')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='HsnCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField(db_index=True, editable=False)),
                ('deathdate', models.DateField(db_index=True, editable=False, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('name', cz_utils.django.db.fields.TrimmedCharField(max_length=1023)),
                ('number', cz_utils.django.db.fields.TrimmedCharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('tax_rate_cgst', cz_utils.django.db.fields.CzTaxPercentField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tax_rate_sgst', cz_utils.django.db.fields.CzTaxPercentField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tax_rate_igst', cz_utils.django.db.fields.CzTaxPercentField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tax_rate_cess', cz_utils.django.db.fields.CzTaxPercentField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_official', models.BooleanField(null=True, blank=True, help_text='Whether this is in the official list publised by GSTN.')),
                ('is_goods', models.BooleanField()),
            ],
            options={
                'ordering': ('number',),
                'default_permissions': (),
                'unique_together': {('is_goods', 'number', 'birthdate')},
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField(help_text='The number of this Document Type.')),
                ('name', cz_utils.django.db.fields.TrimmedCharField(help_text='The name of the Document Type.', max_length=255)),
            ],
            options={
                'ordering': ('number',),
                'default_permissions': (),
                'unique_together': {('number',)},
            },
        ),
    ]
