# Generated by Django 5.2 on 2025-04-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxmaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='is_home',
            field=models.BooleanField(blank=True, help_text='is this the home currency for your company?. If not,\n        leave this field unset. Only one currency can be the home\n        currency.', null=True, unique=True),
        ),
    ]
