/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type DbColumns = string[];
export type FieldConfig = DbColumnConfig | ConstantConfig;

export interface DbChooseColumnsEntrypointArg {
  id: string;
  dbColumns: DbColumns;
  invoicingSpec: MappingSpec;
  exampleData: ExampleData;
  initialColumnMapping: ColumnMapping;
  urls: Urls;
  table: string;
}
export interface MappingSpec {
  sections: MappingSpecSection[];
}
export interface MappingSpecSection {
  name: string;
  description: string;
  fields: MappingSpecField[];
}
export interface MappingSpecField {
  name: string;
  displayName: string;
  help: string | null;
  required: boolean;
}
export interface ExampleData {
  [k: string]: any;
}
export interface ColumnMapping {
  [k: string]: FieldConfig;
}
export interface DbColumnConfig {
  type: "column";
  column: string;
  transformation: string | null;
}
export interface ConstantConfig {
  type: "constant";
  value: string;
  transformation: string | null;
}
export interface Urls {
  setDataMapping: string;
  setColumnMapped: string;
}
