# Generated by Django 5.2 on 2026-03-13 04:57

import cz_utils.django.db.fields
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import invoicing.models
import jsonfield.fields
import re
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxmaster', '0002_alter_currency_is_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('site_name', cz_utils.django.db.fields.TrimmedCharField(default='GSTZen', max_length=255)),
                ('enable_autosync', models.BooleanField(default=False)),
                ('metadata', jsonfield.fields.JSONField(default=dict, editable=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects2', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GlobalConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', cz_utils.django.db.fields.TrimmedCharField(default='GSTZen', max_length=255)),
                ('metadata', jsonfield.fields.JSONField(default=dict, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PermanentAccountNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', cz_utils.django.db.fields.CzUppercaseField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='The specified number is not a valid PAN.', regex=re.compile('^[A-Z]{4}[A-Z0-9][0-9]{4}[A-Z]$', 2))], verbose_name='PAN Number')),
                ('name', cz_utils.django.db.fields.TrimmedCharField(max_length=255, verbose_name='Tax Payer Name')),
                ('metadata', jsonfield.fields.JSONField(default=dict, editable=False)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='GstIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('gstin', cz_utils.django.db.fields.CzUppercaseField(max_length=255, unique=True, validators=[invoicing.models.validate_gstin], verbose_name='GSTIN')),
                ('name', cz_utils.django.db.fields.TrimmedCharField(max_length=255, verbose_name='Tax Payer Name')),
                ('invoice_contact_information', cz_utils.django.db.fields.CzTextField(blank=True, verbose_name='Contact Information (for Invoice)')),
                ('invoice_notes', cz_utils.django.db.fields.CzTextField(blank=True, verbose_name='Notes (for Invoice)')),
                ('registration_date', cz_utils.django.db.fields.CzDateField(blank=True, null=True)),
                ('cancellation_date', cz_utils.django.db.fields.CzDateField(blank=True, null=True)),
                ('taxpayer_type', models.PositiveSmallIntegerField(choices=[(11708, 'Regular Tax Payer'), (11709, 'Composition Tax Payer')], default=11708, help_text='The type of taxpayer.')),
                ('metadata', jsonfield.fields.JSONField(default=dict, editable=False)),
                ('state', cz_utils.django.db.fields.CzForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taxmaster.state')),
                ('permanentaccountnumber', cz_utils.django.db.fields.CzForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoicing.permanentaccountnumber')),
            ],
            options={
                'verbose_name': 'GSTIN',
                'ordering': ('permanentaccountnumber__name', 'state__name'),
            },
        ),
        migrations.CreateModel(
            name='CachedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('datatype', models.PositiveSmallIntegerField(choices=[(17230, 'Purchase Session Marker'), (17231, 'Purchase Errors'), (17232, 'Purchase Summary'), (17233, 'Purchase Finish')])),
                ('data_bytes', models.BinaryField(blank=True, help_text='Binary/bytes data.', null=True)),
                ('data_text', models.TextField(blank=True, help_text='Data in text format.')),
                ('data_json', jsonfield.fields.JSONField(default=dict, editable=False, help_text='Data in JSON format.', null=True)),
                ('group', cz_utils.django.db.fields.CzForeignKey(blank=True, help_text='The related Cached Data (to signify that these related items are part of a single group. Payload and chunks all link to the same Summary.', null=True, on_delete=django.db.models.deletion.PROTECT, to='invoicing.cacheddata')),
                ('gstin', cz_utils.django.db.fields.CzForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='invoicing.gstin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('doctype', models.PositiveSmallIntegerField(choices=[(5697, 'Invoice'), (5698, 'Note')])),
                ('docsubtype', models.PositiveSmallIntegerField(choices=[(4240, 'Not Applicable'), (4241, 'Credit Note'), (4242, 'Debit Note')])),
                ('financial_year', cz_utils.django.db.fields.CzDateField(help_text='The first date of the financial year of the Invoice')),
                ('date', cz_utils.django.db.fields.CzDateField(help_text='The date of the invoice')),
                ('number', cz_utils.django.db.fields.CzUppercaseField(max_length=16, validators=[django.core.validators.RegexValidator(message='The specified number is not a valid Invoice number.', regex='^[A-Z0-9-/]{1,16}$')])),
                ('ctin', cz_utils.django.db.fields.CzUppercaseField(blank=True, max_length=255, verbose_name='Counter Party GSTIN')),
                ('purchase_status', models.PositiveSmallIntegerField(choices=[(84, 'Non-Candidate'), (85, 'Candidate'), (86, 'Uploaded'), (87, 'Error')], help_text='Field to indicate the status of Purchase Invoice sync')),
                ('purchase_json', jsonfield.fields.JSONField(default=dict, dump_kwargs={'cls': invoicing.models.InvoicingJsonEncoder}, editable=False)),
                ('purchase_response', jsonfield.fields.JSONField(default=dict, dump_kwargs={'cls': invoicing.models.InvoicingJsonEncoder}, editable=False)),
                ('metadata', jsonfield.fields.JSONField(default=dict, dump_kwargs={'cls': invoicing.models.InvoicingJsonEncoder}, editable=False)),
                ('upload_uuid', models.UUIDField(editable=False, null=True)),
                ('configuration', cz_utils.django.db.fields.CzForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoicing.configuration')),
                ('gstin', cz_utils.django.db.fields.CzForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoicing.gstin')),
            ],
            options={
                'unique_together': {('gstin', 'ctin', 'doctype', 'financial_year', 'number')},
            },
        ),
    ]
