[supervisord]
logfile=%(here)s/supervisord.log    ; (main log file;default $CWD/supervisord.log)
logfile_maxbytes=50MB               ; (max main logfile bytes b4 rotation;default 50MB)
logfile_backups=10                  ; (num of main logfile rotation backups;default 10)
loglevel=info                       ; (log level;default info; others: debug,warn,trace)
pidfile=%(here)s/supervisord.pid    ; (supervisord pidfile;default supervisord.pid)
nodaemon=true                       ; (start in foreground if true;default false)
silent=false                        ; no logs to stdout if true; default false
minfds=1024                         ; (min. avail startup file descriptors;default 1024)
minprocs=200                        ; (min. avail process descriptors;default 200)
environment=DJANGO_SETTINGS_MODULE="config.settings.development"

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=http://127.0.0.1:8000 ; use an http:// url to specify an inet socket
username=chris              ; should be same as in [*_http_server] if set
password=123                ; should be same as in [*_http_server] if set

[program:runserver]
command="%(here)s\runserver.bat"
priority=2
startretries=1
startsecs=5
stderr_logfile=%(here)s\new-runserver.err
stdout_logfile=%(here)s\new-runserver.log

[program:run_tasks]
priority=3
command="%(here)s\run_tasks.bat"
startretries=1
startsecs=5
stderr_logfile=%(here)s\new-run_tasks.err
stdout_logfile=%(here)s\new-run_tasks.log
autorestart=false

[program:populate_states]
priority=1
command="%(here)s\populate_states.bat"
startretries=1
startsecs=5
stderr_logfile=%(here)s\new-populate_states.err
stdout_logfile=%(here)s\new-populate_states.log
autorestart=false

[program:pythonpath]
priority=4
command="%(here)s\pythonpath.bat"
startretries=1
startsecs=5
stderr_logfile=%(here)s\new-pythonpath.err
stdout_logfile=%(here)s\new-pythonpath.log
autorestart=false
