"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 3.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

import environ
from django.contrib import messages

# /path/to/gst-comply.git/projects/invoicing-local-UI/config/settings/base.py - 3 = /path/to/gst-comply.git/projects/invoicing-local-UI
ROOT_DIR = environ.Path(__file__) - 3
PROJECT_NAME = "config"
PROJECT_DIR = ROOT_DIR.path(PROJECT_NAME)

env = environ.Env()

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

LOG_LEVEL = "DEBUG"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "q!a#vxlx73!-w%mb)xuw-zd+f)oyq$5z1c#ly&=(m=54ab8_xq"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["127.0.0.1", "localhost"]

if env.str("ALLOWED_HOSTS_EXTRA", default=""):
    ALLOWED_HOSTS.append(env.str("ALLOWED_HOSTS_EXTRA"))


# Application definition

INSTALLED_APPS = [
    "invoicing",
    "cz_utils",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "bootstrap_pagination",
    "bootstrap4",
    "crispy_forms",
    "crispy_bootstrap4",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_extensions",
    "taxmaster",
    "gstnapi",
    "django.contrib.humanize",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    # "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"
INVOICING_PDF_URL = "https://my.gstzen.in/~gstzen/a/invoicing-json-to-pdf/display/.pdf/"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [str(ROOT_DIR.path("config/templates"))],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.routing.application"

CHANNEL_LAYERS = {"default": {"BACKEND": "channels.layers.InMemoryChannelLayer"}}

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
    },
}
DEFAULT_AUTO_FIELD = "django.db.models.AutoField"


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = "/static/"

STATIC_ROOT = str(ROOT_DIR.path(".staticfiles"))

# See: https://docs.djangoproject.com/en/dev/ref/contrib/staticfiles/#std:setting-STATICFILES_DIRS
STATICFILES_DIRS = (str(PROJECT_DIR.path("static")),)

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap4"
CRISPY_TEMPLATE_PACK = "bootstrap4"

FORCE_SOFTWARE_ERROR = False

# Override Django message tags to match Bootstrap alert levels
# https://docs.djangoproject.com/en/1.7/ref/contrib/messages/#message-tags
# http://getbootstrap.com/components/#alerts
MESSAGE_TAGS = {
    messages.DEBUG: "info",
    messages.ERROR: "danger",
}

# A sample logging configuration. The only tangible logging
# performed by this configuration is to send an email to
# the site admins on every HTTP 500 error when DEBUG=False.
# See http://docs.djangoproject.com/en/dev/topics/logging for
# more details on how to customize your logging configuration.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {"format": "%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s"},
        "simple": {"format": "%(levelname)s %(message)s"},
    },
    "filters": {"require_debug_false": {"()": "django.utils.log.RequireDebugFalse"}},
    "handlers": {
        "mail_admins": {
            "level": "ERROR",
            "filters": ["require_debug_false"],
            "class": "django.utils.log.AdminEmailHandler",
        },
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django.request": {
            "handlers": ["mail_admins"],
            "level": "ERROR",
            "propagate": True,
        },
        "__main__": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": True,
        },
        "taxmaster": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": True,
        },
        "gstnapi": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": True,
        },
        "invoicing": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": True,
        },
        "pygstn": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": True,
        },
    },
}

CZ_MAX_NUM_SCHEDULED_TASKS = 30
IS_TESTING = False

TO_IRP_THROUGH_ZEN = env.bool("TO_IRP_THROUGH_ZEN", default=True)
"""
Whether to go to IRP through GSTZen or directly

Set this in development.secret since it depends on the user's preference
"""
INVOICING_INPUT_PATH = env.str("INVOICING_INPUT_PATH", default="")
INVOICING_WRITEBACK_PATH = env.str("INVOICING_WRITEBACK_PATH", default="")
INVOICING_ERROR_PATH = env.str("INVOICING_ERROR_PATH", default="")
